---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ns-nse-composition

resources:
- ns.yaml
- sfc.yaml
- client.yaml
- nse-nat
- server.yaml


patches:
- path: server-patch.yaml

configMapGenerator:
  - name: nginx-config
    files:
      - nginx.conf
